"""
output/formatter.py — Render ExtractionResult to Markdown and JSON files.
"""

import json
from pathlib import Path
from datetime import datetime

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from models import ExtractionResult


def _slug(title: str) -> str:
    """Convert title to a safe filename slug."""
    return "".join(c if c.isalnum() or c in "-_" else "_" for c in title)[:60]


def save_markdown(result: ExtractionResult, output_dir: str = "data") -> str:
    """
    Write the extraction result as a clean Markdown file.

    Returns:
        Path to the written file
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    slug = _slug(result.title)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = Path(output_dir) / f"{slug}_{ts}.md"

    lines = [
        f"# {result.title}",
        f"\n> *Generated by Video Note Extractor — {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n",
        "## Summary\n",
        result.summary,
        "\n## Key Concepts\n",
        " · ".join(f"`{c}`" for c in result.key_concepts),
        "\n## Notes\n",
    ]

    for note in result.notes:
        ts_part = f"**{note.timestamp}** — " if note.timestamp else ""
        lines.append(f"### {ts_part}{note.heading}\n")
        lines.append(f"{note.content}\n")

    lines += [
        "\n## Action Items\n",
        *[f"- [ ] {item}" for item in result.action_items],
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def save_json(result: ExtractionResult, output_dir: str = "data") -> str:
    """
    Write the extraction result as JSON.

    Returns:
        Path to the written file
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    slug = _slug(result.title)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = Path(output_dir) / f"{slug}_{ts}.json"

    path.write_text(
        json.dumps(result.model_dump(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return str(path)